### ISSUE TITLE
Is rel still in alpha release stage ?

### ISSUE THREAD

**Issue by sreerajkksd** [bubbleboy14/registeredeventlistener#11]
It looks like rel is still show with "Development Status :: 3 - Alpha" classifier. Is that accurate even now ? If not, Can we change the status ?

**Comment by bubbleboy14** [comment]
@sreerajkksd I just changed it to "5 - Production/Stable":

https://github.com/bubbleboy14/registeredeventlistener/commit/db67af684650c8915b7ee279969a813d438ecaf7

Thanks, good call!
