### ISSUE TITLE
MyPy failed with rel

### ISSUE THREAD

**Issue by helios-code** [bubbleboy14/registeredeventlistener#13]
src/main.py:8: error: Skipping analyzing "rel": module is installed, but missing library stubs or py.typed marker  [import-untyped]

I got this error error while running mypy with rel inside the project and couldn't find a fix.

you gave a section in this documentation, section missing import. 

https://mypy.readthedocs.io/en/stable/running_mypy.html

**Comment by bubbleboy14** [comment]
Thanks for bringing this to my attention, @helios-code !

I generated stubs with stubgen, and mypy now says "Success: no issues found in 9 source files".

Try rel version 0.4.9.8 (just released), and LMK if you have any issues.
