### ISSUE TITLE
Add url to project on pypi

### ISSUE THREAD

**Issue by glensc** [bubbleboy14/registeredeventlistener#14]
Coming from pypi it's not possible to locate source repository of this project:
- https://pypi.org/project/rel/

I got the link to rel from some other project documentation:
- https://websocket-client.readthedocs.io/en/latest/examples.html#dispatching-multiple-websocketapps

Why?

because the description there is so brief that I don't understand what it does or how it works, so need to see source:
> Project description
>
> Select preferred event notification methods with initialize([methods in order of preference]). If initialize(…) is not called, methods are tried in default order: epoll,kqueue,poll,select,pyevent.

**Comment by bubbleboy14** [comment]
Good point @glensc, thanks for noticing!

I updated the pypi page with a slightly longer description and a link to the code and docs here on github.

Thanks again!
