### ISSUE TITLE
Please provide a documentation for rel

### ISSUE THREAD

**Issue by tharindusathis** [bubbleboy14/registeredeventlistener#8]
As no any documentation is present currently, it is very difficult to find how to use the rel. Having a good documentation will be really helpful.

**Comment by anshibanov** [comment]
+1

**Comment by bubbleboy14** [comment]
@tharindusathis @anshibanov sorry, just saw this and added some docs here: https://github.com/bubbleboy14/registeredeventlistener#readme

It's sort of a first pass, but I'm happy to flesh it out. Are there any specific functionalities that are unclear, or questions you'd like answered? Or types of examples you'd like to see?

**Comment by bubbleboy14** [comment]
Closing for now. Feel free to reopen if anyone wants more/better docs on any particular subject.
